#
#EPITECH PROJECT, 2021
#Tek2
#File description:
#docker-compose.yml
#

version: "3.3"


##===SERVICES===========>

services:

## -- Poll ------------->
  poll:
    restart: always
    depends_on:
      - worker
    build: poll

    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier


## -- Redis ------------>
  redis:
    restart: always
    image: redis:6.2-alpine

    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier

## -- Worker ----------->
  worker:
    restart: always
    depends_on:
      - redis
      - db
    build: worker

    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    networks:
      - back-tier

## -- Result ----------->
  result:
    restart: always
    depends_on:
      - db
    build: result

    environment:
      - PORT=80
      - DB_HOST=db
    ports:
      - "5001:80"
    networks:
      - result-tier

## -- DataBase --------->
  db:
    restart: always
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


##======================>


##===VOLUMES===========>

volumes:
  db-data:

##======================>


##===NETWORKS===========>

networks:
  poll-tier:
  result-tier:
  back-tier:

##======================>